FROM python:3.9.17-slim-bookworm

ARG PROJECT_DIR=.

# Update pip
RUN pip install --upgrade pip

RUN apt update && apt install -y curl
RUN curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.4.0 python -
# add poetry to path
ENV PATH="/root/.local/bin:${PATH}"


# Copy and modify paths to local monorepo libs in poetry files
# to ensure recursive dependencies are resolved correctly.
COPY ${PROJECT_DIR}/pyproject.toml ${PROJECT_DIR}/poetry.lock ./
COPY ${PROJECT_DIR}/app ./app

RUN poetry config virtualenvs.create true
RUN poetry config virtualenvs.in-project true
RUN poetry install
RUN poetry install --extras "debugpy"

ENV env=debug

CMD ["poetry", "run", "uvicorn", "app.server.main:app", "--reload", "--host", "0.0.0.0", "--port", "20409"]
